### ISSUE TITLE
Wk 7 - Wireframe Task 3 - Executive  Pages

### ISSUE THREAD

**Issue by Turbs24** [Turbs24/IFB299-Project-67#19]
Reporting pages, define how the reports should look, how they function, explain access and kinda of permissions required for this pages. 
- Should be versatile but also streamline
- Consider the user to be someone who needs to be catered to, they arent heavily technically literate but they also require complex results from their actions
- Should utilise buttons and drop down menus
- Results should be tables and graphs

**Comment by GitDude100** [comment]
[Executive pages.pptx](https://github.com/Turbs24/IFB299-Project-67/files/2374123/Executive.pages.pptx)
